//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلق.
        /// </summary>
        public static string Absolute {
            get {
                return ResourceManager.GetString("Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برحسب.
        /// </summary>
        public static string AccordingTo {
            get {
                return ResourceManager.GetString("AccordingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گرایش فعالیت.
        /// </summary>
        public static string ActivityOrientation {
            get {
                return ResourceManager.GetString("ActivityOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماینده.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک آپارات.
        /// </summary>
        public static string aparat {
            get {
                return ResourceManager.GetString("aparat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر های ارسالی معتبر نیستند.
        /// </summary>
        public static string ApiResultStatusCodeBadRequest {
            get {
                return ResourceManager.GetString("ApiResultStatusCodeBadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست خالی است.
        /// </summary>
        public static string ApiResultStatusCodeListEmpty {
            get {
                return ResourceManager.GetString("ApiResultStatusCodeListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در پردازش رخ داد.
        /// </summary>
        public static string ApiResultStatusCodeLogicError {
            get {
                return ResourceManager.GetString("ApiResultStatusCodeLogicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یافت نشد.
        /// </summary>
        public static string ApiResultStatusCodeNotFound {
            get {
                return ResourceManager.GetString("ApiResultStatusCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در سرور رخ داده است.
        /// </summary>
        public static string ApiResultStatusCodeServerError {
            get {
                return ResourceManager.GetString("ApiResultStatusCodeServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        public static string ApiResultStatusCodeSuccess {
            get {
                return ResourceManager.GetString("ApiResultStatusCodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای احراز هویت.
        /// </summary>
        public static string ApiResultStatusCodeUnAuthorized {
            get {
                return ResourceManager.GetString("ApiResultStatusCodeUnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول عمر کد مجوز.
        /// </summary>
        public static string AuthorizationCodeLifetime {
            get {
                return ResourceManager.GetString("AuthorizationCodeLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام رسان آی گپ.
        /// </summary>
        public static string ay_gp {
            get {
                return ResourceManager.GetString("ay_gp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام رسان آیتا.
        /// </summary>
        public static string ayta {
            get {
                return ResourceManager.GetString("ayta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سشن کانال برگشت خروج ضروری است.
        /// </summary>
        public static string BackChannelLogoutSessionRequired {
            get {
                return ResourceManager.GetString("BackChannelLogoutSessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایت دیگر.
        /// </summary>
        public static string blank {
            get {
                return ResourceManager.GetString("blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام رسان بله.
        /// </summary>
        public static string blh {
            get {
                return ResourceManager.GetString("blh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله /خیر.
        /// </summary>
        public static string boolean {
            get {
                return ResourceManager.GetString("boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هردو.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باکس چت انلاین .
        /// </summary>
        public static string Boxchat {
            get {
                return ResourceManager.GetString("Boxchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برند.
        /// </summary>
        public static string BrandTitle {
            get {
                return ResourceManager.GetString("BrandTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خراب شده.
        /// </summary>
        public static string Broken {
            get {
                return ResourceManager.GetString("Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساختمان.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلاس دکمه.
        /// </summary>
        public static string ButtonClass {
            get {
                return ResourceManager.GetString("ButtonClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان دکمه.
        /// </summary>
        public static string ButtonTitle {
            get {
                return ResourceManager.GetString("ButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر دکمه.
        /// </summary>
        public static string ButtonUrl {
            get {
                return ResourceManager.GetString("ButtonUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ.
        /// </summary>
        public static string ByColor {
            get {
                return ResourceManager.GetString("ByColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خودرو.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت.
        /// </summary>
        public static string CartNumber {
            get {
                return ResourceManager.GetString("CartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت کارت.
        /// </summary>
        public static string CartStatus {
            get {
                return ResourceManager.GetString("CartStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دسته بندی.
        /// </summary>
        public static string CategoryCount {
            get {
                return ResourceManager.GetString("CategoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع نمایش دسته.
        /// </summary>
        public static string CategoryScm {
            get {
                return ResourceManager.GetString("CategoryScm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دسته.
        /// </summary>
        public static string CategoryType {
            get {
                return ResourceManager.GetString("CategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شناسنامه.
        /// </summary>
        public static string CertificateId {
            get {
                return ResourceManager.GetString("CertificateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهرستان.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محرمانگی.
        /// </summary>
        public static string Confidentiality {
            get {
                return ResourceManager.GetString("Confidentiality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید شده.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتویات متا.
        /// </summary>
        public static string ContentMenta {
            get {
                return ResourceManager.GetString("ContentMenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ بدون هویت.
        /// </summary>
        public static string ConutCartNotIdentity {
            get {
                return ResourceManager.GetString("ConutCartNotIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت .
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت توسط نام و نام خانوادگی.
        /// </summary>
        public static string CreatedFullName {
            get {
                return ResourceManager.GetString("CreatedFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت توسط اکانت.
        /// </summary>
        public static string CreatedUserName {
            get {
                return ResourceManager.GetString("CreatedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی فعلی.
        /// </summary>
        public static string CurrentAmount {
            get {
                return ResourceManager.GetString("CurrentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور فعلی.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی مشتری.
        /// </summary>
        public static string CustomerFullName {
            get {
                return ResourceManager.GetString("CustomerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل مشتری.
        /// </summary>
        public static string CustomerMobile {
            get {
                return ResourceManager.GetString("CustomerMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی مشتری.
        /// </summary>
        public static string CustomerNationalCode {
            get {
                return ResourceManager.GetString("CustomerNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string DateTimeAdd {
            get {
                return ResourceManager.GetString("DateTimeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string DeActive {
            get {
                return ResourceManager.GetString("DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کالا.
        /// </summary>
        public static string DefinedCount {
            get {
                return ResourceManager.GetString("DefinedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دپارتمان.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات سئو.
        /// </summary>
        public static string DescriptionSeo {
            get {
                return ResourceManager.GetString("DescriptionSeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابزار.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string Diasable {
            get {
                return ResourceManager.GetString("Diasable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نمایشی.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راننده.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اهمیت دادن.
        /// </summary>
        public static string Emphasize {
            get {
                return ResourceManager.GetString("Emphasize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند.
        /// </summary>
        public static string Employer {
            get {
                return ResourceManager.GetString("Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خالی - پیش فرض.
        /// </summary>
        public static string EmptyPage {
            get {
                return ResourceManager.GetString("EmptyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود محلی را فعال کنید.
        /// </summary>
        public static string EnableLocalLogin {
            get {
                return ResourceManager.GetString("EnableLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماهیت کسب و کار.
        /// </summary>
        public static string Essence {
            get {
                return ResourceManager.GetString("Essence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضا.
        /// </summary>
        public static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضاء.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیس بوک.
        /// </summary>
        public static string facebook {
            get {
                return ResourceManager.GetString("facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب طرح.
        /// </summary>
        public static string FacilityTitle {
            get {
                return ResourceManager.GetString("FacilityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیکون سایت.
        /// </summary>
        public static string Favicons {
            get {
                return ResourceManager.GetString("Favicons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکس.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صدور پروانه.
        /// </summary>
        public static string FileIssuedUrl {
            get {
                return ResourceManager.GetString("FileIssuedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالی.
        /// </summary>
        public static string Financial {
            get {
                return ResourceManager.GetString("Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فونت آیکون.
        /// </summary>
        public static string FontIcon {
            get {
                return ResourceManager.GetString("FontIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبورتان را فراموش کرده اید؟.
        /// </summary>
        public static string Forgotyourpassword {
            get {
                return ResourceManager.GetString("Forgotyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تاریخ.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سشن کانال جلو خروج ضروری است.
        /// </summary>
        public static string FrontChannelLogoutSessionRequired {
            get {
                return ResourceManager.GetString("FrontChannelLogoutSessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri کانال جلو خروج.
        /// </summary>
        public static string FrontChannelLogoutUri {
            get {
                return ResourceManager.GetString("FrontChannelLogoutUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ونام خانوداگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع گیت.
        /// </summary>
        public static string GateType {
            get {
                return ResourceManager.GetString("GateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع پروتکل.
        /// </summary>
        public static string GetProtocolTypes {
            get {
                return ResourceManager.GetString("GetProtocolTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع واگذاری مجاز.
        /// </summary>
        public static string GrantType {
            get {
                return ResourceManager.GetString("GrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی نگهبان.
        /// </summary>
        public static string GuardFullName {
            get {
                return ResourceManager.GetString("GuardFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری نگهبان.
        /// </summary>
        public static string GuardUserName {
            get {
                return ResourceManager.GetString("GuardUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه صنفی.
        /// </summary>
        public static string GuildId {
            get {
                return ResourceManager.GetString("GuildId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دکمه دارد.
        /// </summary>
        public static string HasButton {
            get {
                return ResourceManager.GetString("HasButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان عکس.
        /// </summary>
        public static string ImageAltText {
            get {
                return ResourceManager.GetString("ImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش زمینه.
        /// </summary>
        public static string ImageBack {
            get {
                return ResourceManager.GetString("ImageBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات عکس.
        /// </summary>
        public static string ImageDesc {
            get {
                return ResourceManager.GetString("ImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شامل Jwt Id.
        /// </summary>
        public static string IncludeJwtId {
            get {
                return ResourceManager.GetString("IncludeJwtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درحال بررسی.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورودی.
        /// </summary>
        public static string InPut {
            get {
                return ResourceManager.GetString("InPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گیت ورود.
        /// </summary>
        public static string InputGateTitle {
            get {
                return ResourceManager.GetString("InputGateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شغل خود را وارد نمایید..
        /// </summary>
        public static string InsertJobTitle {
            get {
                return ResourceManager.GetString("InsertJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اینستاگرام.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پلاک عمومی.
        /// </summary>
        public static string InternationalPlate {
            get {
                return ResourceManager.GetString("InternationalPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آی پی.
        /// </summary>
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شهر پلاک.
        /// </summary>
        public static string IranCode {
            get {
                return ResourceManager.GetString("IranCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش بعنوان فیلتر.
        /// </summary>
        public static string IsFilter {
            get {
                return ResourceManager.GetString("IsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در صفحه اصلی.
        /// </summary>
        public static string IsFirst {
            get {
                return ResourceManager.GetString("IsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت افراد ناشناس.
        /// </summary>
        public static string IsSaveNonUser {
            get {
                return ResourceManager.GetString("IsSaveNonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در ویترین صفحه اول.
        /// </summary>
        public static string IsShowHome {
            get {
                return ResourceManager.GetString("IsShowHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ صدور.
        /// </summary>
        public static string IssueDate {
            get {
                return ResourceManager.GetString("IssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شغل.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولین.
        /// </summary>
        public static string keyValue {
            get {
                return ResourceManager.GetString("keyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناخته شده.
        /// </summary>
        public static string Known {
            get {
                return ResourceManager.GetString("Known", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین لاگین.
        /// </summary>
        public static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز قبلی.
        /// </summary>
        public static string LastPassword {
            get {
                return ResourceManager.GetString("LastPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک لینکدین.
        /// </summary>
        public static string linkedin {
            get {
                return ResourceManager.GetString("linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک یا اسکریپ سئو.
        /// </summary>
        public static string LinkSeo {
            get {
                return ResourceManager.GetString("LinkSeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت جغرافیایی.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاگ ورود مهمانها.
        /// </summary>
        public static string LogGuest {
            get {
                return ResourceManager.GetString("LogGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوگو.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوگو Uri.
        /// </summary>
        public static string LogoUri {
            get {
                return ResourceManager.GetString("LogoUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه بومی - موبایل/دسکتاپ جریان کد مجوز با PKCE.
        /// </summary>
        public static string MachinePage {
            get {
                return ResourceManager.GetString("MachinePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازار یا مجتمع.
        /// </summary>
        public static string Mall {
            get {
                return ResourceManager.GetString("Mall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران کارگزار.
        /// </summary>
        public static string ManageBrokerUsers {
            get {
                return ResourceManager.GetString("ManageBrokerUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازاریاب.
        /// </summary>
        public static string Marketer {
            get {
                return ResourceManager.GetString("Marketer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد معرف.
        /// </summary>
        public static string MarketingCodeStore {
            get {
                return ResourceManager.GetString("MarketingCodeStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر زمان مراجعه.
        /// </summary>
        public static string MaxDate {
            get {
                return ResourceManager.GetString("MaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جلسه.
        /// </summary>
        public static string Meeting {
            get {
                return ResourceManager.GetString("Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید درخواست های جلسه همکاران.
        /// </summary>
        public static string MeetingConfirm {
            get {
                return ResourceManager.GetString("MeetingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ جلسه.
        /// </summary>
        public static string MeetingDate {
            get {
                return ResourceManager.GetString("MeetingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک ملت.
        /// </summary>
        public static string Mellat {
            get {
                return ResourceManager.GetString("Mellat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع عضویت.
        /// </summary>
        public static string MembershipType {
            get {
                return ResourceManager.GetString("MembershipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منو.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متا.
        /// </summary>
        public static string Meta {
            get {
                return ResourceManager.GetString("Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل زمان مراجعه.
        /// </summary>
        public static string MinDate {
            get {
                return ResourceManager.GetString("MinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در حاشیه.
        /// </summary>
        public static string MiniImage {
            get {
                return ResourceManager.GetString("MiniImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرم افزار موبایل.
        /// </summary>
        public static string MobileApplication {
            get {
                return ResourceManager.GetString("MobileApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماژول.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آقا.
        /// </summary>
        public static string Mr {
            get {
                return ResourceManager.GetString("Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانم.
        /// </summary>
        public static string Mrs {
            get {
                return ResourceManager.GetString("Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چندانتخابی.
        /// </summary>
        public static string MultiSelective {
            get {
                return ResourceManager.GetString("MultiSelective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایت من.
        /// </summary>
        public static string MySite {
            get {
                return ResourceManager.GetString("MySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کارمند قرار ملاقات.
        /// </summary>
        public static string NameEmployee {
            get {
                return ResourceManager.GetString("NameEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string NameFather {
            get {
                return ResourceManager.GetString("NameFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام متا.
        /// </summary>
        public static string NameMeta {
            get {
                return ResourceManager.GetString("NameMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر کارت ملی.
        /// </summary>
        public static string NationalCardImage {
            get {
                return ResourceManager.GetString("NationalCardImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور جدید.
        /// </summary>
        public static string NewConfirmPassword {
            get {
                return ResourceManager.GetString("NewConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون رنگ.
        /// </summary>
        public static string NotColor {
            get {
                return ResourceManager.GetString("NotColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عددی.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره باز پرداخت(ماه).
        /// </summary>
        public static string NumberFacilityPlanTitle {
            get {
                return ResourceManager.GetString("NumberFacilityPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمینه شغلی.
        /// </summary>
        public static string OccupationalField {
            get {
                return ResourceManager.GetString("OccupationalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کارمندان.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدارک کارمندان.
        /// </summary>
        public static string OfficeDocument {
            get {
                return ResourceManager.GetString("OfficeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط یک بار.
        /// </summary>
        public static string OneTimeOnly {
            get {
                return ResourceManager.GetString("OneTimeOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ترتیب.
        /// </summary>
        public static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چارت سازمان.
        /// </summary>
        public static string OrganizationalChart {
            get {
                return ResourceManager.GetString("OrganizationalChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشکیلات سازمان.
        /// </summary>
        public static string OrganizationalPosition {
            get {
                return ResourceManager.GetString("OrganizationalPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت سازمانی.
        /// </summary>
        public static string OrganizationalPosition1 {
            get {
                return ResourceManager.GetString("OrganizationalPosition1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروجی.
        /// </summary>
        public static string OutPut {
            get {
                return ResourceManager.GetString("OutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرمجموعه.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک پارسیان.
        /// </summary>
        public static string Parsian {
            get {
                return ResourceManager.GetString("Parsian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت همکاران.
        /// </summary>
        public static string PartnerManagement {
            get {
                return ResourceManager.GetString("PartnerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در پرداخت.
        /// </summary>
        public static string PaymentError {
            get {
                return ResourceManager.GetString("PaymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درحال بررسی.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افراد.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع پلاک.
        /// </summary>
        public static string PlateType {
            get {
                return ResourceManager.GetString("PlateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدوده پلاک.
        /// </summary>
        public static string PlateZone {
            get {
                return ResourceManager.GetString("PlateZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI های مجاز به تغییر مسیر پس از خروج را مشخص می کند.
        /// </summary>
        public static string PostLogoutRedirectUri {
            get {
                return ResourceManager.GetString("PostLogoutRedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت(برحسب تومان).
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پراپرتی.
        /// </summary>
        public static string ProductPropertyTitle {
            get {
                return ResourceManager.GetString("ProductPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد محصولات.
        /// </summary>
        public static string ProductsCount {
            get {
                return ResourceManager.GetString("ProductsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول.
        /// </summary>
        public static string ProductTitle {
            get {
                return ResourceManager.GetString("ProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عکس پروفایل.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ویژگی ها.
        /// </summary>
        public static string PropertyCount {
            get {
                return ResourceManager.GetString("PropertyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارائه دهنده.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهرستان.
        /// </summary>
        public static string Provincee {
            get {
                return ResourceManager.GetString("Provincee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد لایک.
        /// </summary>
        public static string RateCount {
            get {
                return ResourceManager.GetString("RateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوانده شده.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر.
        /// </summary>
        public static string RedirectUri {
            get {
                return ResourceManager.GetString("RedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقضاء رفرش توکن.
        /// </summary>
        public static string RefreshTokenExpiration {
            get {
                return ResourceManager.GetString("RefreshTokenExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربرد رفرش توکن.
        /// </summary>
        public static string RefreshTokenUsage {
            get {
                return ResourceManager.GetString("RefreshTokenUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد شده.
        /// </summary>
        public static string Refused {
            get {
                return ResourceManager.GetString("Refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت درخواست.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نیازمند رمز سرویس گیرنده.
        /// </summary>
        public static string RequireClientSecret {
            get {
                return ResourceManager.GetString("RequireClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نیازمند موافقت.
        /// </summary>
        public static string RequireConsent {
            get {
                return ResourceManager.GetString("RequireConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضروری.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوباره استفاده کنید.
        /// </summary>
        public static string ReUse {
            get {
                return ResourceManager.GetString("ReUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش .
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش در زنجیره تامین.
        /// </summary>
        public static string RoleSupplyChain {
            get {
                return ResourceManager.GetString("RoleSupplyChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع نقش.
        /// </summary>
        public static string RoleType {
            get {
                return ResourceManager.GetString("RoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار مخفی.
        /// </summary>
        public static string SecretValue {
            get {
                return ResourceManager.GetString("SecretValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان تایید شده پایان جلسه توسط مامور امنیتی.
        /// </summary>
        public static string SecurityForceConfirmedMeetingFinished {
            get {
                return ResourceManager.GetString("SecurityForceConfirmedMeetingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان تایید شده شروع جلسه توسط مامور امنیتی.
        /// </summary>
        public static string SecurityForceConfirmedMeetingStarted {
            get {
                return ResourceManager.GetString("SecurityForceConfirmedMeetingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواست به تومان.
        /// </summary>
        public static string SelectPrice {
            get {
                return ResourceManager.GetString("SelectPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب محصول.
        /// </summary>
        public static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب ویژگی.
        /// </summary>
        public static string SelectProperty {
            get {
                return ResourceManager.GetString("SelectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد احراز هویت شما {0} می باشد..
        /// </summary>
        public static string sendSmsCode {
            get {
                return ResourceManager.GetString("sendSmsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر مورد نظر.
        /// </summary>
        public static string SeoUrl {
            get {
                return ResourceManager.GetString("SeoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش بعنوان فیلتر.
        /// </summary>
        public static string ShowAsFilter {
            get {
                return ResourceManager.GetString("ShowAsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش در سند کشف.
        /// </summary>
        public static string ShowInDiscoveryDocument {
            get {
                return ResourceManager.GetString("ShowInDiscoveryDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الگوریتم های امضای توکن دسترسی مجاز است.
        /// </summary>
        public static string SigningAlgorithms {
            get {
                return ResourceManager.GetString("SigningAlgorithms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکی.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان سایت.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشویی.
        /// </summary>
        public static string Sliding {
            get {
                return ResourceManager.GetString("Sliding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول عمر اسلایدینگ رفرش توکن.
        /// </summary>
        public static string SlidingRefreshTokenLifetime {
            get {
                return ResourceManager.GetString("SlidingRefreshTokenLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامک.
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه تک صفحه ای - جاوااسکریپت جریان کد مجوز با PKCE.
        /// </summary>
        public static string SpaPage {
            get {
                return ResourceManager.GetString("SpaPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام رسان سروش.
        /// </summary>
        public static string srwsh {
            get {
                return ResourceManager.GetString("srwsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت کاربر.
        /// </summary>
        public static string StatusUser {
            get {
                return ResourceManager.GetString("StatusUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشگاه.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسب و کار.
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کسب وکار.
        /// </summary>
        public static string StoreType {
            get {
                return ResourceManager.GetString("StoreType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوشتاری.
        /// </summary>
        public static string StringType {
            get {
                return ResourceManager.GetString("StringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد زیر فیلترها.
        /// </summary>
        public static string SubFilterCount {
            get {
                return ResourceManager.GetString("SubFilterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موفقیت آمیز.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی ثبت نام شما با موفقیت انجام شد
        ///نام کاربری : {0}
        ///کلمه عبور : {1}.
        /// </summary>
        public static string SuccessfullyRegistered {
            get {
                return ResourceManager.GetString("SuccessfullyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش در زنجیره تامین.
        /// </summary>
        public static string SupplyChainRole {
            get {
                return ResourceManager.GetString("SupplyChainRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبانی.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلگرام.
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متنی.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدرهگیری.
        /// </summary>
        public static string TrackingCode {
            get {
                return ResourceManager.GetString("TrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک تویتیر.
        /// </summary>
        public static string twitter {
            get {
                return ResourceManager.GetString("twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فیلد.
        /// </summary>
        public static string TypeProp {
            get {
                return ResourceManager.GetString("TypeProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سئو.
        /// </summary>
        public static string TypeSeo {
            get {
                return ResourceManager.GetString("TypeSeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تگ لینک.
        /// </summary>
        public static string TypeSeoLink {
            get {
                return ResourceManager.GetString("TypeSeoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکریپ.
        /// </summary>
        public static string TypeSeoScript {
            get {
                return ResourceManager.GetString("TypeSeoScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string UnKnown {
            get {
                return ResourceManager.GetString("UnKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادعاهای توکن دسترسی با تازه سازی بروز شود.
        /// </summary>
        public static string UpdateAccessTokenClaimsOnRefresh {
            get {
                return ResourceManager.GetString("UpdateAccessTokenClaimsOnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خریدار.
        /// </summary>
        public static string UserBuyer {
            get {
                return ResourceManager.GetString("UserBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول عمر Sso کاربر.
        /// </summary>
        public static string UserSsoLifetime {
            get {
                return ResourceManager.GetString("UserSsoLifetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد بازدید.
        /// </summary>
        public static string Visitcount {
            get {
                return ResourceManager.GetString("Visitcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وب سایت.
        /// </summary>
        public static string WebApplication {
            get {
                return ResourceManager.GetString("WebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه وب - سمت سرور جریان کد مجوز با PKCE.
        /// </summary>
        public static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفته.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک واتساپ.
        /// </summary>
        public static string whatsapp {
            get {
                return ResourceManager.GetString("whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک یوتیوب.
        /// </summary>
        public static string youtube {
            get {
                return ResourceManager.GetString("youtube", resourceCulture);
            }
        }
    }
}
