//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرکردن تمامی فیلد ها الزامی است.
        /// </summary>
        public static string AllFieldsAreRequired {
            get {
                return ResourceManager.GetString("AllFieldsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا نسبت به {0} اطمینان دارید؟.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا نسبت به سوزاندن این کارت اطمینان دارید؟.
        /// </summary>
        public static string AreYouSureBurnCart {
            get {
                return ResourceManager.GetString("AreYouSureBurnCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ارسالی نادرست می باشد.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر موجودی امکان پذیر نیست.
        /// </summary>
        public static string CanNotChangeCurrentAmount {
            get {
                return ResourceManager.GetString("CanNotChangeCurrentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر فروشنده امکان پذیر نیست.
        /// </summary>
        public static string CanNotChangeSeller {
            get {
                return ResourceManager.GetString("CanNotChangeSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی کد امنیتی اشتباه می باشد لطفا دوباره امتحان کنید..
        /// </summary>
        public static string CAPTCHA {
            get {
                return ResourceManager.GetString("CAPTCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب دسته اجباریست!.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد شهرستان اجباریست.
        /// </summary>
        public static string CityId {
            get {
                return ResourceManager.GetString("CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} با فیلد {1} برابر نیست.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز کاربر با هم برابر نیست.
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی شما قادر به حذف این رکورد نیستید..
        /// </summary>
        public static string DearuserDeleteRecord {
            get {
                return ResourceManager.GetString("DearuserDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی عنوان مورد نظر در سامانه وجود دارد.
        /// </summary>
        public static string DearUserDesiredTitleSystem {
            get {
                return ResourceManager.GetString("DearUserDesiredTitleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی فیلد نقش نباید خالی باشد.
        /// </summary>
        public static string Dearuserrolefieldmpty {
            get {
                return ResourceManager.GetString("Dearuserrolefieldmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستگاه مورد نظر معتبر نیست.
        /// </summary>
        public static string DeviceNotValid {
            get {
                return ResourceManager.GetString("DeviceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی اکانت شما  غیرفعال شده لطفا جهت فعال سازی گزینه ارسال مجدد رمز عبور را بزنید .
        /// </summary>
        public static string DisAccount {
            get {
                return ResourceManager.GetString("DisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت شما شما مسدود میباشد لطفا با مدیرسایت تماس بگیرین.
        /// </summary>
        public static string DisActiveUser {
            get {
                return ResourceManager.GetString("DisActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پیگیری قبلاً در پایگاه داده وجود دارد. برای هر درخواست از یک مورد منحصر به فرد استفاده کنید..
        /// </summary>
        public static string DuplicateTrackingNumber {
            get {
                return ResourceManager.GetString("DuplicateTrackingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید به صورت انگلیسی تایپ شود.
        /// </summary>
        public static string EnPassword {
            get {
                return ResourceManager.GetString("EnPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سایت به صورت انگلیسی تایپ نمایید.
        /// </summary>
        public static string EnSiteName {
            get {
                return ResourceManager.GetString("EnSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید به صورت انگلیسی تایپ شود.
        /// </summary>
        public static string EnUserName {
            get {
                return ResourceManager.GetString("EnUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد اس ام اس درست نمی باشد..
        /// </summary>
        public static string equalCodeSms {
            get {
                return ResourceManager.GetString("equalCodeSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی فیلد انتخاب نقش اجباری می باشد.
        /// </summary>
        public static string ErrorMessageRoleIds {
            get {
                return ResourceManager.GetString("ErrorMessageRoleIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی سیستم دچار خطا شده است لطفا با پشتیبانی تماس بگیرین.
        /// </summary>
        public static string ErrorSelectusertype {
            get {
                return ResourceManager.GetString("ErrorSelectusertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال اس ام اس ناموفق بوده لطفا دوباره امتحان کنید.
        /// </summary>
        public static string ErrorSendSms {
            get {
                return ResourceManager.GetString("ErrorSendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا از سمت سرور لطفا دوباره امتحان کنید.
        /// </summary>
        public static string ErrorServer {
            get {
                return ResourceManager.GetString("ErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی اطلاعات مورد نظر با خطا مواجه شده لطفا دوباره امتحان کنید.
        /// </summary>
        public static string ErrorServiceScanner {
            get {
                return ResourceManager.GetString("ErrorServiceScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی لطفا کارت ملی مورد نظر را وارد نمایید.
        /// </summary>
        public static string ErrorUploadCard {
            get {
                return ResourceManager.GetString("ErrorUploadCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد نام اجباریست.
        /// </summary>
        public static string FristName {
            get {
                return ResourceManager.GetString("FristName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز کارت هدیه اشتباه می یاشد لطفا دوباره امتحان نمایید.
        /// </summary>
        public static string GiftCardError {
            get {
                return ResourceManager.GetString("GiftCardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز کارت هدیه اشتباه می باشد.
        /// </summary>
        public static string GiftCardRegex {
            get {
                return ResourceManager.GetString("GiftCardRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی دچار خطا شده است لطفا بعداز دو دقیقه دیگر امتحان کنید..
        /// </summary>
        public static string GoogleReCAPTCHA {
            get {
                return ResourceManager.GetString("GoogleReCAPTCHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری در سامانه وجود دارد.
        /// </summary>
        public static string HasUserName {
            get {
                return ResourceManager.GetString("HasUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی لطفا عکس مورد نظر را آپلود کنید .
        /// </summary>
        public static string imageValid {
            get {
                return ResourceManager.GetString("imageValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گواهی نامه نامعتبر.
        /// </summary>
        public static string invalidcredentials {
            get {
                return ResourceManager.GetString("invalidcredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های نامعتبر از دروازه دریافت می شود..
        /// </summary>
        public static string InvalidDataReceivedFromGateway {
            get {
                return ResourceManager.GetString("InvalidDataReceivedFromGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL برگشت نامعتبر است.
        /// </summary>
        public static string invalidreturnURL {
            get {
                return ResourceManager.GetString("invalidreturnURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز ورود نامعتبر است.
        /// </summary>
        public static string Invalidusernameorpassword {
            get {
                return ResourceManager.GetString("Invalidusernameorpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل وجود فاکتور اجازه حذف را ندارید..
        /// </summary>
        public static string isFactoreNotDelete {
            get {
                return ResourceManager.GetString("isFactoreNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا در سامانه ثبت شده است.
        /// </summary>
        public static string IsInDataCreate {
            get {
                return ResourceManager.GetString("IsInDataCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تکراری است.
        /// </summary>
        public static string IsNotUniq {
            get {
                return ResourceManager.GetString("IsNotUniq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان مورد نظر در سامانه تکراری می باشد.
        /// </summary>
        public static string IsNotUniqTitle {
            get {
                return ResourceManager.GetString("IsNotUniqTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی شما عضو کارمندان اتحادیه می باشید .
        /// </summary>
        public static string isuseraccess {
            get {
                return ResourceManager.GetString("isuseraccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد نام خانوادگی اجباریست.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  کاربر گرامی تعداد کاراکتر .
        /// </summary>
        public static string LengthCustome {
            get {
                return ResourceManager.GetString("LengthCustome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کارکترهای وارد شده نباید بیشتر از ({1}) باشد..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر طول کلمه عبور 12 کاراکتر است.
        /// </summary>
        public static string MaxLength12 {
            get {
                return ResourceManager.GetString("MaxLength12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی اندازه فایل بیشتر 200 کیلو بایت نباشد.
        /// </summary>
        public static string MaxSizeFile200K {
            get {
                return ResourceManager.GetString("MaxSizeFile200K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی اندازه فایل بیشتر 500 کیلو بایت نباشد.
        /// </summary>
        public static string MaxSizeFile500K {
            get {
                return ResourceManager.GetString("MaxSizeFile500K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجوز عبور ندارید، زمان مراجعه برای این ملاقات از ساعت {0} تا {1} می باشد.
        /// </summary>
        public static string MeetingDateIsNotTrue {
            get {
                return ResourceManager.GetString("MeetingDateIsNotTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کارکترهای وارد شده نباید کمتر از ({0}) باشد..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور نمیتواند کمتر از 6 کاراکتر باشد.
        /// </summary>
        public static string MinLength6 {
            get {
                return ResourceManager.GetString("MinLength6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات باموفقیت انجام شد..
        /// </summary>
        public static string MissionAccomplished {
            get {
                return ResourceManager.GetString("MissionAccomplished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد شده نادرست است.
        /// </summary>
        public static string MobileIsNotInCorrectFormat {
            get {
                return ResourceManager.GetString("MobileIsNotInCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد کد ملی اجباریست.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی اشتباه می باشد..
        /// </summary>
        public static string NationalIdValid {
            get {
                return ResourceManager.GetString("NationalIdValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز جدید با رمز قبلی نباید یکی باشد.
        /// </summary>
        public static string NewPasswordNotPreviousPassword {
            get {
                return ResourceManager.GetString("NewPasswordNotPreviousPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نا شناس.
        /// </summary>
        public static string nonuser {
            get {
                return ResourceManager.GetString("nonuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی کدملی مورد نظر ناشناس می باشد..
        /// </summary>
        public static string nonuserError {
            get {
                return ResourceManager.GetString("nonuserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی فایل مورد نظر به درستی اپلود نشده است لطفا دوباره امتحان کنید..
        /// </summary>
        public static string NoSuccessupload {
            get {
                return ResourceManager.GetString("NoSuccessupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی شما به این درخواست درسترسی ندارید.
        /// </summary>
        public static string NotAllowRequest {
            get {
                return ResourceManager.GetString("NotAllowRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد مورد نظر یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر توسط حراست تایید نشده است.
        /// </summary>
        public static string NotMeetingUserCreateNowDisActive {
            get {
                return ResourceManager.GetString("NotMeetingUserCreateNowDisActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر در سامانه هیچ ملاقاتی ثبت نشده است.
        /// </summary>
        public static string NotMeetingUserCreateTody {
            get {
                return ResourceManager.GetString("NotMeetingUserCreateTody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری مورد نظر یافت نشد.
        /// </summary>
        public static string NotUserNameIsExists {
            get {
                return ResourceManager.GetString("NotUserNameIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد احراز هویت اشتباه می باشد..
        /// </summary>
        public static string NotverifySmsCode {
            get {
                return ResourceManager.GetString("NotverifySmsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری وجود ندارد.
        /// </summary>
        public static string NoUsername {
            get {
                return ResourceManager.GetString("NoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمینه شغلی اجباریست!.
        /// </summary>
        public static string OccupationalFieldId {
            get {
                return ResourceManager.GetString("OccupationalFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فلید نام سازمان / اداره اجباریست.
        /// </summary>
        public static string OfficeId {
            get {
                return ResourceManager.GetString("OfficeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز قبلی شما اشتباه میباشد..
        /// </summary>
        public static string OldPasswrod {
            get {
                return ResourceManager.GetString("OldPasswrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط پرداخت کامل می تواند مسترد شود..
        /// </summary>
        public static string OnlyCompletedPaymentCanBeRefunded {
            get {
                return ResourceManager.GetString("OnlyCompletedPaymentCanBeRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسمت رمز عبور الزامی است.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت به صورت برنامه ای لغو می شود..
        /// </summary>
        public static string PaymentCanceledProgrammatically {
            get {
                return ResourceManager.GetString("PaymentCanceledProgrammatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت ناموفق..
        /// </summary>
        public static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت درخواستی قبلاً پردازش شده است..
        /// </summary>
        public static string PaymentIsAlreadyProcessedBefore {
            get {
                return ResourceManager.GetString("PaymentIsAlreadyProcessedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت با موفقیت انجام شد..
        /// </summary>
        public static string PaymentSucceed {
            get {
                return ResourceManager.GetString("PaymentSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد استان اجباریست.
        /// </summary>
        public static string ProvinceId {
            get {
                return ResourceManager.GetString("ProvinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد شده باید در بازه ({0}) تا ({1}) باشد!.
        /// </summary>
        public static string Rang {
            get {
                return ResourceManager.GetString("Rang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} الزامیست!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب نقش اجباریست..
        /// </summary>
        public static string RoleIds {
            get {
                return ResourceManager.GetString("RoleIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی لطفا یکی از استانها یا گزینه انتخاب همه را انتخاب نمایید.
        /// </summary>
        public static string SelectBetwenProrperty {
            get {
                return ResourceManager.GetString("SelectBetwenProrperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فایل انتخاب شده باید.
        /// </summary>
        public static string showerroforuploadfile1 {
            get {
                return ResourceManager.GetString("showerroforuploadfile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باشد و حجمش کمتر از.
        /// </summary>
        public static string showerroforuploadfile2 {
            get {
                return ResourceManager.GetString("showerroforuploadfile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باشد.
        /// </summary>
        public static string showerroforuploadfile3 {
            get {
                return ResourceManager.GetString("showerroforuploadfile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سایت مورد نظر در سامانه وجود دارد لطفا دوباره امتحان کنید..
        /// </summary>
        public static string SiteNameIsExists {
            get {
                return ResourceManager.GetString("SiteNameIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد کد اس ام اس اجباری می باشد.
        /// </summary>
        public static string SMSCodeRequired {
            get {
                return ResourceManager.GetString("SMSCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد تلفن ثابت باید رشته ای با حداقل طول {0} و حداکثر طول {1} باشد..
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد تلفن ثابت باید رشته ای با حداقل طول 6 و حداکثر طول {1} باشد..
        /// </summary>
        public static string StringLength6 {
            get {
                return ResourceManager.GetString("StringLength6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی شما با موفقیت ثبت نام شدید. لطفا موبایل خود را فعال نمایید.
        /// </summary>
        public static string SuccessfulyRegistered_ConfirmYourMobile {
            get {
                return ResourceManager.GetString("SuccessfulyRegistered_ConfirmYourMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان  مورد نظر در سامانه موجود می باشد.
        /// </summary>
        public static string TitleIsExists {
            get {
                return ResourceManager.GetString("TitleIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل آیتم های وابسته قادر به حذف نیست.
        /// </summary>
        public static string UnableDeleteItems {
            get {
                return ResourceManager.GetString("UnableDeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت شما غیرمجاز است.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای غیرمنتظره.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک خطای ناشناخته روی داده است..
        /// </summary>
        public static string UnexpectedErrorText {
            get {
                return ResourceManager.GetString("UnexpectedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی شما درسترسی به این فرشگاه ندارید.
        /// </summary>
        public static string UserExistsNotInStore {
            get {
                return ResourceManager.GetString("UserExistsNotInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری وارد شده تکراری است.
        /// </summary>
        public static string UserNameIsExists {
            get {
                return ResourceManager.GetString("UserNameIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری به صورت شماره موبایل باشد.
        /// </summary>
        public static string Usernamemobilenumber {
            get {
                return ResourceManager.GetString("Usernamemobilenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسمت نام کاربری الزامی است.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string WrongUsernameOrPassword {
            get {
                return ResourceManager.GetString("WrongUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور اشتباه می باشد..
        /// </summary>
        public static string YourPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("YourPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز قبلی شما اشتباه می باشد.
        /// </summary>
        public static string YourPreviousPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("YourPreviousPasswordIsIncorrect", resourceCulture);
            }
        }
    }
}
