//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Pages", typeof(Pages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات درباره ما.
        /// </summary>
        public static string AboutUsDecs {
            get {
                return ResourceManager.GetString("AboutUsDecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت درباره ما.
        /// </summary>
        public static string AboutUsManagement {
            get {
                return ResourceManager.GetString("AboutUsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلم ها.
        /// </summary>
        public static string AboutUsMovice {
            get {
                return ResourceManager.GetString("AboutUsMovice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش پرداخت ها.
        /// </summary>
        public static string AdminWalletReport {
            get {
                return ResourceManager.GetString("AdminWalletReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع واگذاری مجاز.
        /// </summary>
        public static string AllowedGrantTypes {
            get {
                return ResourceManager.GetString("AllowedGrantTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه/خروج.
        /// </summary>
        public static string AuthenticationLogoutClient {
            get {
                return ResourceManager.GetString("AuthenticationLogoutClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منو اصلی.
        /// </summary>
        public static string BaseMenu {
            get {
                return ResourceManager.GetString("BaseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبانی.
        /// </summary>
        public static string BasicsClient {
            get {
                return ResourceManager.GetString("BasicsClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منو فروشگاه و خدمات.
        /// </summary>
        public static string bothServiceStore {
            get {
                return ResourceManager.GetString("bothServiceStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت برند.
        /// </summary>
        public static string BrandManagement {
            get {
                return ResourceManager.GetString("BrandManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی کالاها.
        /// </summary>
        public static string CategoryHome {
            get {
                return ResourceManager.GetString("CategoryHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت دسته بندی.
        /// </summary>
        public static string CategoryManagement {
            get {
                return ResourceManager.GetString("CategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت شهرستان.
        /// </summary>
        public static string Citymanagement {
            get {
                return ResourceManager.GetString("Citymanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به صفحه اصلی.
        /// </summary>
        public static string Clickhereforthehomepage {
            get {
                return ResourceManager.GetString("Clickhereforthehomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سیستم.
        /// </summary>
        public static string Clickheretologin {
            get {
                return ResourceManager.GetString("Clickheretologin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت سرویس دهنده.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی جدید.
        /// </summary>
        public static string CodeSecurity {
            get {
                return ResourceManager.GetString("CodeSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت رنگ.
        /// </summary>
        public static string ColorlManagement {
            get {
                return ResourceManager.GetString("ColorlManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه موافقت.
        /// </summary>
        public static string ConsentScreenClient {
            get {
                return ResourceManager.GetString("ConsentScreenClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت تماس ها.
        /// </summary>
        public static string ContactUsManagement {
            get {
                return ResourceManager.GetString("ContactUsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد رکورد جدید.
        /// </summary>
        public static string CreateRecord {
            get {
                return ResourceManager.GetString("CreateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت محصولات.
        /// </summary>
        public static string customerproduct {
            get {
                return ResourceManager.GetString("customerproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کالا.
        /// </summary>
        public static string DefinedProductManagement {
            get {
                return ResourceManager.GetString("DefinedProductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کالاها .
        /// </summary>
        public static string DefinedProductMange {
            get {
                return ResourceManager.GetString("DefinedProductMange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کالا .
        /// </summary>
        public static string DefinedProductPage {
            get {
                return ResourceManager.GetString("DefinedProductPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کالای جدید.
        /// </summary>
        public static string DefinedProductPageCreate {
            get {
                return ResourceManager.GetString("DefinedProductPageCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کالا.
        /// </summary>
        public static string DefinedProductPageEdit {
            get {
                return ResourceManager.GetString("DefinedProductPageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولات انتخابی.
        /// </summary>
        public static string DefinedProductSelectPage {
            get {
                return ResourceManager.GetString("DefinedProductSelectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف فایل.
        /// </summary>
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جریان دستگاه.
        /// </summary>
        public static string DeviceFlowClient {
            get {
                return ResourceManager.GetString("DeviceFlowClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت گردش دستگاه.
        /// </summary>
        public static string DeviceFlowManagement {
            get {
                return ResourceManager.GetString("DeviceFlowManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت دستگاه ها.
        /// </summary>
        public static string DeviceManagement {
            get {
                return ResourceManager.GetString("DeviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داکیومنت.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوالات داکیومنت.
        /// </summary>
        public static string DocumentAnswer {
            get {
                return ResourceManager.GetString("DocumentAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل‌ها را برای ارسال، کشیده و در اینجا رها کنید.
        /// </summary>
        public static string dropFilesHere {
            get {
                return ResourceManager.GetString("dropFilesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش رمز عبور.
        /// </summary>
        public static string EditPassword {
            get {
                return ResourceManager.GetString("EditPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پروفایل.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمندان.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالی.
        /// </summary>
        public static string Financial {
            get {
                return ResourceManager.GetString("Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت فونت آیکون ها.
        /// </summary>
        public static string FontIconManagement {
            get {
                return ResourceManager.GetString("FontIconManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت پانویس.
        /// </summary>
        public static string FooterInfoManagement {
            get {
                return ResourceManager.GetString("FooterInfoManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراموشی رمز عبور.
        /// </summary>
        public static string Forgotyourpassword {
            get {
                return ResourceManager.GetString("Forgotyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت هدیه.
        /// </summary>
        public static string GiftCard {
            get {
                return ResourceManager.GetString("GiftCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سخت افزار.
        /// </summary>
        public static string Hardware {
            get {
                return ResourceManager.GetString("Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایان ارسال.
        /// </summary>
        public static string headerStatusUploaded {
            get {
                return ResourceManager.GetString("headerStatusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ارسال فایل‌ها.
        /// </summary>
        public static string headerStatusUploading {
            get {
                return ResourceManager.GetString("headerStatusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست آیکون ها.
        /// </summary>
        public static string iconList {
            get {
                return ResourceManager.GetString("iconList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اگر قبلا  ثبت نام کرده اید، نیاز به ثبت نام مجدد  ندارید.
        /// </summary>
        public static string IfRegisterInSite {
            get {
                return ResourceManager.GetString("IfRegisterInSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درج فایل.
        /// </summary>
        public static string InsertFile {
            get {
                return ResourceManager.GetString("InsertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درج عکس.
        /// </summary>
        public static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ورود نامعتبر است.
        /// </summary>
        public static string Invalidloginrequest {
            get {
                return ResourceManager.GetString("Invalidloginrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صدور پروانه.
        /// </summary>
        public static string Issued {
            get {
                return ResourceManager.GetString("Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایتم.
        /// </summary>
        public static string ItemHome {
            get {
                return ResourceManager.GetString("ItemHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شغل.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا.
        /// </summary>
        public static string Kala {
            get {
                return ResourceManager.GetString("Kala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشخاص حقیقی/حقوقی.
        /// </summary>
        public static string legalPersons {
            get {
                return ResourceManager.GetString("legalPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به زوکار.
        /// </summary>
        public static string logInInSite {
            get {
                return ResourceManager.GetString("logInInSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری.
        /// </summary>
        public static string LoginToAccount {
            get {
                return ResourceManager.GetString("LoginToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم جامع زوکار.
        /// </summary>
        public static string logoTitle {
            get {
                return ResourceManager.GetString("logoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا میخواهید از اکانت مورد نظر خارج شوید؟.
        /// </summary>
        public static string logoutAccount {
            get {
                return ResourceManager.GetString("logoutAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منوی اصلی.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   پذیرنده.
        /// </summary>
        public static string ManageBrokerUsers {
            get {
                return ResourceManager.GetString("ManageBrokerUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امور مالی.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت منو.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات منو.
        /// </summary>
        public static string MenuDesc {
            get {
                return ResourceManager.GetString("MenuDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت منو.
        /// </summary>
        public static string MenuManagement {
            get {
                return ResourceManager.GetString("MenuManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منو خدمات.
        /// </summary>
        public static string MenuService {
            get {
                return ResourceManager.GetString("MenuService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منو فروشگاه.
        /// </summary>
        public static string MenuStore {
            get {
                return ResourceManager.GetString("MenuStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماژول.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کالا های ثبت شده جدید.
        /// </summary>
        public static string NewProductManage {
            get {
                return ResourceManager.GetString("NewProductManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخبار.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اخبار.
        /// </summary>
        public static string NewsDice {
            get {
                return ResourceManager.GetString("NewsDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر جدید هستید؟.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ برنامه ورود به سیستم برای این درخواست پیکربندی نشده است..
        /// </summary>
        public static string Notconfiguredrequest {
            get {
                return ResourceManager.GetString("Notconfiguredrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت دسته بندی زمینه شغلی.
        /// </summary>
        public static string OccupationalFieldCategory {
            get {
                return ResourceManager.GetString("OccupationalFieldCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و ویرایش تنظیمات سئو.
        /// </summary>
        public static string pageHeaderseo {
            get {
                return ResourceManager.GetString("pageHeaderseo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و ویرایش تنظیمات سایت.
        /// </summary>
        public static string pageHeaderSetting {
            get {
                return ResourceManager.GetString("pageHeaderSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زوکار.
        /// </summary>
        public static string PageLayout {
            get {
                return ResourceManager.GetString("PageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم جامع سامانه زوکار.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل مدیریت .
        /// </summary>
        public static string PanelAdmin {
            get {
                return ResourceManager.GetString("PanelAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل کسب وکار.
        /// </summary>
        public static string panelStore {
            get {
                return ResourceManager.GetString("panelStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همکاران.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت محصولات.
        /// </summary>
        public static string ProductManagement {
            get {
                return ResourceManager.GetString("ProductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت ویژگی ها.
        /// </summary>
        public static string ProductPropertyManagement {
            get {
                return ResourceManager.GetString("ProductPropertyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت محصول و دسته بندی.
        /// </summary>
        public static string ProductsCategoryManagement {
            get {
                return ResourceManager.GetString("ProductsCategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت پراپرتی محصولات.
        /// </summary>
        public static string ProductsFilterManagement {
            get {
                return ResourceManager.GetString("ProductsFilterManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل.
        /// </summary>
        public static string ProfileEdit {
            get {
                return ResourceManager.GetString("ProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت شهرستان.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان و شهرستان.
        /// </summary>
        public static string ProvinceAndCity {
            get {
                return ResourceManager.GetString("ProvinceAndCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات مدیریت شهرستان.
        /// </summary>
        public static string ProvinceDic {
            get {
                return ResourceManager.GetString("ProvinceDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت استان.
        /// </summary>
        public static string ProvincialManagement {
            get {
                return ResourceManager.GetString("ProvincialManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri های تغییر مسیر.
        /// </summary>
        public static string RedirectUris {
            get {
                return ResourceManager.GetString("RedirectUris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت ‌نام در ‌زوکار.
        /// </summary>
        public static string RegisterYourName {
            get {
                return ResourceManager.GetString("RegisterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود من را بخاطر بسپار.
        /// </summary>
        public static string RememberMyLogin {
            get {
                return ResourceManager.GetString("RememberMyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منبع.
        /// </summary>
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Claim.
        /// </summary>
        public static string ResourceClaim {
            get {
                return ResourceManager.GetString("ResourceClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات منبع.
        /// </summary>
        public static string ResourceDesc {
            get {
                return ResourceManager.GetString("ResourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Property.
        /// </summary>
        public static string ResourceProperty {
            get {
                return ResourceManager.GetString("ResourceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Scopes.
        /// </summary>
        public static string ResourceScopes {
            get {
                return ResourceManager.GetString("ResourceScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Secrets.
        /// </summary>
        public static string ResourceSecrets {
            get {
                return ResourceManager.GetString("ResourceSecrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعی مجدد.
        /// </summary>
        public static string retryFile {
            get {
                return ResourceManager.GetString("retryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت صنف.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داکیومنت.
        /// </summary>
        public static string RoleDocument {
            get {
                return ResourceManager.GetString("RoleDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت صنف.
        /// </summary>
        public static string Rolemanagement {
            get {
                return ResourceManager.GetString("Rolemanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت دسترسی.
        /// </summary>
        public static string Rolemanagementadmin {
            get {
                return ResourceManager.GetString("Rolemanagementadmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کارکنان.
        /// </summary>
        public static string RolesAndUsers {
            get {
                return ResourceManager.GetString("RolesAndUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اسکوپ.
        /// </summary>
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScopeClaim.
        /// </summary>
        public static string ScopeClaim {
            get {
                return ResourceManager.GetString("ScopeClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اسکوپ.
        /// </summary>
        public static string ScopeDecs {
            get {
                return ResourceManager.GetString("ScopeDecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScopeProperty.
        /// </summary>
        public static string ScopeProperty {
            get {
                return ResourceManager.GetString("ScopeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب فایل‌ها برای ارسال.
        /// </summary>
        public static string SelectForUpload {
            get {
                return ResourceManager.GetString("SelectForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        public static string Serviec {
            get {
                return ResourceManager.GetString("Serviec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سئو.
        /// </summary>
        public static string settingseo {
            get {
                return ResourceManager.GetString("settingseo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سایت.
        /// </summary>
        public static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش فایل.
        /// </summary>
        public static string ShowFile {
            get {
                return ResourceManager.GetString("ShowFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف این فایل مطمئن هستید؟.
        /// </summary>
        public static string ShowFileError {
            get {
                return ResourceManager.GetString("ShowFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف این فایل مطمئن هستید؟.
        /// </summary>
        public static string ShowWarring {
            get {
                return ResourceManager.GetString("ShowWarring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل کاربری.
        /// </summary>
        public static string signintosite {
            get {
                return ResourceManager.GetString("signintosite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سایت.
        /// </summary>
        public static string SiteSettings {
            get {
                return ResourceManager.GetString("SiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسلایدر.
        /// </summary>
        public static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات عکس.
        /// </summary>
        public static string SliderDic {
            get {
                return ResourceManager.GetString("SliderDic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اسلایدر.
        /// </summary>
        public static string SliderManagement {
            get {
                return ResourceManager.GetString("SliderManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ارسال.
        /// </summary>
        public static string statusFailed {
            get {
                return ResourceManager.GetString("statusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال شد.
        /// </summary>
        public static string statusUploaded {
            get {
                return ResourceManager.GetString("statusUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ارسال.
        /// </summary>
        public static string statusUploading {
            get {
                return ResourceManager.GetString("statusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخطار.
        /// </summary>
        public static string statusWarning {
            get {
                return ResourceManager.GetString("statusWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسب و کارهای تایید شده.
        /// </summary>
        public static string StoreAccept {
            get {
                return ResourceManager.GetString("StoreAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسب و کارهای پیش فرض.
        /// </summary>
        public static string StoreBase {
            get {
                return ResourceManager.GetString("StoreBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسب و کارهای اقساطی(اعتباری).
        /// </summary>
        public static string StoreCredit {
            get {
                return ResourceManager.GetString("StoreCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسب و کارهای تمام شده.
        /// </summary>
        public static string StoreEnd {
            get {
                return ResourceManager.GetString("StoreEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کسب و کار ها.
        /// </summary>
        public static string Storemanage {
            get {
                return ResourceManager.GetString("Storemanage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسب و کارهای جدید.
        /// </summary>
        public static string StoreNew {
            get {
                return ResourceManager.GetString("StoreNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اخبار.
        /// </summary>
        public static string StoreNewsManagement {
            get {
                return ResourceManager.GetString("StoreNewsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسب و کارهای خریداری نشده.
        /// </summary>
        public static string StoreNotPay {
            get {
                return ResourceManager.GetString("StoreNotPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شغل خود را وارد نمایید.
        /// </summary>
        public static string StorePageTitle {
            get {
                return ResourceManager.GetString("StorePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسب و کارهای رد شده.
        /// </summary>
        public static string StoreRece {
            get {
                return ResourceManager.GetString("StoreRece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت زیر فیلترها.
        /// </summary>
        public static string SubFilterManagement {
            get {
                return ResourceManager.GetString("SubFilterManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن.
        /// </summary>
        public static string TokenClient {
            get {
                return ResourceManager.GetString("TokenClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی تردد براساس کارت ملی.
        /// </summary>
        public static string TrafficCheckCard {
            get {
                return ResourceManager.GetString("TrafficCheckCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتیجه اطلاعات کارت ملی.
        /// </summary>
        public static string TrafficCheckCardInfo {
            get {
                return ResourceManager.GetString("TrafficCheckCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال فایل‌ها.
        /// </summary>
        public static string uploadSelectedFiles {
            get {
                return ResourceManager.GetString("uploadSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیف پول.
        /// </summary>
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما از برنامه خارج شده اید.
        /// </summary>
        public static string Youarenowloggedout {
            get {
                return ResourceManager.GetString("Youarenowloggedout", resourceCulture);
            }
        }
    }
}
